name: Deploy to GitHub Pages

# Kör workflow vid push till main eller manuellt
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Rättigheter för GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Endast en deployment åt gången
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout koden
      - uses: actions/checkout@v4

      # Installera .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Bygg och publisha projektet
      - name: Publish .NET Project
        run: dotnet publish WeddingQuiz.csproj -c Release -o release --nologo

      # Ändra base-tag i index.html till ditt GitHub Pages repo
      - name: Change base-tag in index.html
        run: |
          sed -i 's|<base href="/" />|<base href="/WeddingQuiz/" />|g' release/wwwroot/index.html

      # Lägg till .nojekyll för att GitHub Pages inte ska tolka _ mappar
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

        # Lägg till efter .nojekyll
      - name: Add _redirects file
        run: echo "/* /index.html 200" > release/wwwroot/_redirects

      # Ladda upp artifacts för deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'release/wwwroot'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4